# Generated by Django 5.0.2 on 2024-03-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musicimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicimg',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music', verbose_name='Песня'),
        ),
    ]
