# Generated by Django 5.0.2 on 2024-03-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_musicimg_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicimg',
            old_name='img',
            new_name='images',
        ),
    ]
