# Generated by Django 5.0.2 on 2024-03-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_img_musicimg_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicimg',
            name='post',
        ),
        migrations.AddField(
            model_name='music',
            name='music_images',
            field=models.ManyToManyField(to='music.musicimg'),
        ),
    ]
