# Generated by Django 5.0.2 on 2024-03-04 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_rename_music_images_music_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='images',
        ),
        migrations.AddField(
            model_name='musicimg',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='music.music'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicimg',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
    ]
